---
kind: Service
apiVersion: v1
metadata:
  name: greeting-processor
spec:
  selector:
    app: greeting-processor
  ports:
    - port: 8080
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: greeting-processor
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: greeting-processor
    spec:
      containers:
      - name: greeting-processor
        image: docker.example.com/greeting-processor:1
        imagePullPolicy: Always
        env:
        - name: PROCESSOR_GREETING
          valueFrom:
            configMapKeyRef:
              name: greeting-processor-config
              key: processor.greeting
      imagePullSecrets:
      - name: regsecret
      restartPolicy: Always
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: greeting-processor-config
data:
  processor.greeting: Hi
---